export class CampaignDayObject {
  // date: string;
  // adgroup_id: string;
  // taps: number;
  // matchType: string;
  // avg_cpt: number;
  // re_downloads: number;
  // keywordStatus: string;
  // avg_cpa: number;
  // lat_off_installs: number;
  // keyword: string;
  // conversion_rate: number;
  // campaign_id: string;
  // lat_on_installs: number;
  // local_spend: number;
  // adgroup_deleted: string;
  // impressions: number;
  // installs: number;
  // deleted: boolean;
  // ttr: number;
  // keyword_id: string;
  // org_id: string;
  // keywordDisplayStatus: string;
  // bid: number;
  // new_downloads: number;
  // modification_time: string;
  // adgroup_name: string;

  branch_commerce_event_count: number;
  taps: number;
  avg_cpt: number;
  displayStatus: string;
  re_downloads: number;
  servingStatus: string;
  modificationTime: string;
  avg_cpa: number;
  lat_off_installs: number;
  campaignStatus: string;
  branch_revenue: number;
  conversion_rate: number;
  campaign_id: string;
  timestamp: string;
  lat_on_installs: number;
  campaignId: string;
  appName: string;
  dailyBudget_amount: number;
  totalBudget_currency: string;
  local_spend: string;
  installs: number;
  ttr: number;
  dailyBudget_currency: string;
  deleted: boolean;
  totalBudget_amount: string;
  org_id: string;
  new_downloads: number;
  campaignName: string;
  adamId: string;
}
